channels:
  - conda-forge
dependencies:
  - python>=3.7.0,<3.8
  - pandoc
  - ipython
  - pip
  - pip:
    - wheel
    - sphinx_rtd_theme
    - nbsphinx
    - git+https://github.com/cimm-kzn/CGRtools.git@master#egg=CGRtools[mrv]
    - .
